bboard/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.urls import include, path
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('debug/', include('debug_toolbar.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

bboard/main/urls.py
from django.urls import path
from main.views import (BBLoginView, BBLogoutView, BBPasswordChangeView,
                        BBPasswordResetCompleteView,
                        BBPasswordResetConfirmView, BBPasswordResetDoneView,
                        BBPasswordResetView, ChangeUserInfoView,
                        DeleteUserView, RegisterDoneView, RegisterUserView,
                        index, other_page, profile, user_activate)

app_name = 'main'

urlpatterns = [
    path(
        'accounts/password/confirm/<uidb64>/<token>/',
        BBPasswordResetConfirmView.as_view(), name='password_reset_confirm'
    ),
    path(
        'accounts/password/confirm/complete/',
        BBPasswordResetCompleteView.as_view(), name='password_reset_complete'
    ),
    path(
        'accounts/password/reset/done/', BBPasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'accounts/register/activate/<str:sign>/', user_activate,
        name='register_activate'
    ),
    path(
        'accounts/password/reset/', BBPasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'accounts/password/change/', BBPasswordChangeView.as_view(),
        name='password_change'
    ),
    path(
        'accounts/profile/delete/', DeleteUserView.as_view(),
        name='profile_delete'
    ),
    path(
        'accounts/profile/change/', ChangeUserInfoView.as_view(),
        name='profile_change'
    ),
    path(
        'accounts/register/done/', RegisterDoneView.as_view(),
        name='register_done'
    ),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

bboard/templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Главная{% endblock %} - Доска объявлений</title>
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='slim' %}
    </head>
    <body class="container-fluid">
        <header class="mb-4">
            <h1 class="display-1 text-center">Объявления</h1>
        </header>
        <div class="row">
            <ul class="col nav justify-content-end border">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Профиль</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Мои объявления</a>
                        <a class="dropdown-item" href="#">Изменить личные данные</a>
                        <a class="dropdown-item" href="#">Изменить пароль</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Выйти</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Удалить</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Вход</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="row">
            <nav class="col-md-auto nav flex-column border">
                <a class="nav-link root" href="{% url 'main:index' %}">Главная</a>
                <a class="nav-link root" href="{% url 'main:other' page='about' %}">О сайте</a>
            </nav>
            <section class="col border py-2">
                {% bootstrap_messages %}
                {% block content %}
                {% endblock %}
            </section>
        </div>
        <footer class="mt-3">
            <p class="text-right font-italic">&copy; читатели.</p>
        </footer>
    </body>
</html>